#!/bin/bash 
rawArgs="$@" 
ldFix="-lrt" 

if [[ -z "${RealCppCompilerAndLinker}" ]]; then
	RealCppCompilerAndLinker=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
fi

if [[ -z "${libSystemPath}" ]]; then
	libSystemPath=$RUNTIME_REPO/artifacts/bin/runtime/net7.0-Android-Release-arm64/
fi

globalizationPath=$libSystemPath"libSystem.Globalization.Native.a" 
securityPath=$libSystemPath"libSystem.Net.Security.Native.a" 
sslPath=$libSystemPath"libSystem.Security.Cryptography.Native.OpenSsl.a" 
fixedArgs=${rawArgs//$ldFix/}
fixedArgs=${fixedArgs//$globalizationPath/} 
fixedArgs=${fixedArgs//$securityPath/}
fixedArgs=${fixedArgs//$sslPath/} 

$RealCppCompilerAndLinker $fixedArgs 
