#!/bin/bash
rawArgs="$@"
ldrt="-lrt"
ldlog="-llog"
globalizationPath=$libSystemPath"libSystem.Globalization.Native.a"
securityPath=$libSystemPath"libSystem.Net.Security.Native.a"
sslPath=$libSystemPath"libSystem.Security.Cryptography.Native.OpenSsl.a"
fixedArgs=${rawArgs//$ldrt/ldlog}
fixedArgs=${fixedArgs//$globalizationPath/}
fixedArgs=${fixedArgs//$securityPath/}
fixedArgs=${fixedArgs//$sslPath/}

echo $RealCppCompilerAndLinker" "$fixedArgs

$RealCppCompilerAndLinker $fixedArgs